# Site settings
source:         "src"
title:          "ElevenRoute"
email:          "contact@11route.com"
author:         "Anatoliy Yastreb"
author_twitter: "https://twitter.com/mrHabicht"
blog_twitter:   "elevenroute"
blog_github:    "https://github.com/ayastreb/11route"
description:    "Anatoliy Yastreb's travel blog. I write here about all the places I visit and share my experiences."
keywords:
  - travel blog
  - photo blog
  - tourist photos
  - landscape phots
  - travel in europe
  - spain photos
  - italy photos
  - germany photos
  - what to see in europe
  - interesting places
  - travel tips
baseurl:        ""
url:            "https://11route.com"
date_format:    "%B %-d, %Y"
# Localization
languages:
  en: "English"
  ru: "Русский"
navigation:
  map:
    url:
      en: "en/map"
      ru: "map"
    label:
      en: "Map"
      ru: "Карта"
  contact:
    en: "Contact"
    ru: "Контакт"
feed:
  en: "feed.en.xml"
  ru: "feed.xml"
# Google analytics
# Google services
google_analytics: "UA-48431990-1"
google_verification:

maps:
  google:
    api_key: "AIzaSyCESuhc2nS2LDpp9pU9P1YJsxTAAOoQGE4"

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "11route"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
sass:
  compressed: true
plugins:
  - jekyll-maps
  - jemoji
